move Almanac.png 							d:\projects\popcap\pvz\datasource\loc\en\images
move background1.png						d:\projects\popcap\pvz\datasource\loc\en\images 
move background1unsodded.png                d:\projects\popcap\pvz\datasource\loc\en\images 
move background2.png                        d:\projects\popcap\pvz\datasource\loc\en\images 
move background3_clothesline.png            d:\projects\popcap\pvz\datasource\loc\en\images 
move Challenge_Thumbnails.png               d:\projects\popcap\pvz\datasource\loc\en\images 
move chocolate.png                          d:\projects\popcap\pvz\datasource\loc\en\images 
move coinbank.png                           d:\projects\popcap\pvz\datasource\loc\en\images 
move Credits_ZombieNote.png                 d:\projects\popcap\pvz\datasource\loc\en\images 
move Fertilizer.png                         d:\projects\popcap\pvz\datasource\loc\en\images 
move FlagMeterLevelProgress.png             d:\projects\popcap\pvz\datasource\loc\en\images 
move help_menu_image_achmt.png              d:\projects\popcap\pvz\datasource\loc\en\images 
move help_menu_image_coop_butter.png        d:\projects\popcap\pvz\datasource\loc\en\images 
move help_menu_image_coop_menu.png          d:\projects\popcap\pvz\datasource\loc\en\images 
move help_menu_image_coop_sun.png           d:\projects\popcap\pvz\datasource\loc\en\images 
move ImitaterSeed.png                       d:\projects\popcap\pvz\datasource\loc\en\images 
move ImitaterSeedDisabled.png               d:\projects\popcap\pvz\datasource\loc\en\images 
move licensePlate_1N1RTRE.png               d:\projects\popcap\pvz\datasource\loc\en\images 
move licensePlate_BUYSMTN.png               d:\projects\popcap\pvz\datasource\loc\en\images 
move licensePlate_FLORFUD.png               d:\projects\popcap\pvz\datasource\loc\en\images 
move licensePlate_GR8DLZ.png                d:\projects\popcap\pvz\datasource\loc\en\images 
move licensePlate_IMCR8Z.png                d:\projects\popcap\pvz\datasource\loc\en\images 
move licensePlate_MAD4GRVY.png              d:\projects\popcap\pvz\datasource\loc\en\images 
move licensePlate_MEAMDAV.png               d:\projects\popcap\pvz\datasource\loc\en\images 
move licensePlate_RDWARER.png               d:\projects\popcap\pvz\datasource\loc\en\images 
move licensePlate_SMTNFNY.png               d:\projects\popcap\pvz\datasource\loc\en\images 
move licensePlate_SODALID.png               d:\projects\popcap\pvz\datasource\loc\en\images 
move licensePlate_UNEMPLD.png               d:\projects\popcap\pvz\datasource\loc\en\images 
move licensePlate_VRMVRM.png                d:\projects\popcap\pvz\datasource\loc\en\images 
move mail_background_zombiepostcard.png     d:\projects\popcap\pvz\datasource\loc\en\images 
move mail_message_coop.png                  d:\projects\popcap\pvz\datasource\loc\en\images 
move mail_message_intro.png                 d:\projects\popcap\pvz\datasource\loc\en\images 
move mail_overlay_stpatricks.png            d:\projects\popcap\pvz\datasource\loc\en\images 
move mail_overlay_text1.png                 d:\projects\popcap\pvz\datasource\loc\en\images 
move mail_overlay_text2.png                 d:\projects\popcap\pvz\datasource\loc\en\images 
move moneybag.png                           d:\projects\popcap\pvz\datasource\loc\en\images 
move moneybag_hi_res.png                    d:\projects\popcap\pvz\datasource\loc\en\images 
move options_menuback.jpg                   d:\projects\popcap\pvz\datasource\loc\en\images 
move p1_text.png                            d:\projects\popcap\pvz\datasource\loc\en\images 
move p2_text.png                            d:\projects\popcap\pvz\datasource\loc\en\images 
move plant_side_plants.png                  d:\projects\popcap\pvz\datasource\loc\en\images 
move PvZ_Logo.png                           d:\projects\popcap\pvz\datasource\loc\en\images 
move Store_Car.png                          d:\projects\popcap\pvz\datasource\loc\en\images 
move Store_Car_night.png                    d:\projects\popcap\pvz\datasource\loc\en\images 
move Store_ComingSoonLabel.png              d:\projects\popcap\pvz\datasource\loc\en\images 
move Store_ExtraSlotLabel.png               d:\projects\popcap\pvz\datasource\loc\en\images 
move Store_PvZIcon.png                      d:\projects\popcap\pvz\datasource\loc\en\images 
move Store_Sign.png                         d:\projects\popcap\pvz\datasource\loc\en\images 
move Store_SoldOutLabel.png                 d:\projects\popcap\pvz\datasource\loc\en\images 
move survival_button.png                    d:\projects\popcap\pvz\datasource\loc\en\images 
move Tombstones.jpg                         d:\projects\popcap\pvz\datasource\loc\en\images 
move TreeFood.png                           d:\projects\popcap\pvz\datasource\loc\en\images 
move win.png                                d:\projects\popcap\pvz\datasource\loc\en\images 
move Zen_MoneySign.png                      d:\projects\popcap\pvz\datasource\loc\en\images 
move zenshopbutton.png                      d:\projects\popcap\pvz\datasource\loc\en\images 
move zenshopbutton_highlight.png            d:\projects\popcap\pvz\datasource\loc\en\images 
move Zombie_bobsled1.png                    d:\projects\popcap\pvz\datasource\loc\en\images 
move Zombie_bobsled2.png                    d:\projects\popcap\pvz\datasource\loc\en\images 
move Zombie_bobsled3.png                    d:\projects\popcap\pvz\datasource\loc\en\images 
move Zombie_bobsled4.png                    d:\projects\popcap\pvz\datasource\loc\en\images 
move zombie_side_zombies.png                d:\projects\popcap\pvz\datasource\loc\en\images 
move Zombiefinalnote.png                    d:\projects\popcap\pvz\datasource\loc\en\images 
move ZombieNote1.png                        d:\projects\popcap\pvz\datasource\loc\en\images 
move ZombieNote2.png                        d:\projects\popcap\pvz\datasource\loc\en\images 
move ZombieNote3.png                        d:\projects\popcap\pvz\datasource\loc\en\images 
move ZombieNote4.png                        d:\projects\popcap\pvz\datasource\loc\en\images 
move ZombieNoteHelp.png                     d:\projects\popcap\pvz\datasource\loc\en\images 

